name: Release

on:
  push:
    branches:
      - release

jobs:
  bump-version-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Bump version
        id: bump
        run: |
          cz bump --yes --increment PATCH
          NEW_VERSION=$(python -c 'exec(open("version.py").read()); print(__version__)')
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git add version.py CHANGELOG.md
          git commit -m "chore: bump version to ${{ env.new_version }}"
          git tag v${{ env.new_version }}
          git push origin release --tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.new_version }}
          release_name: Release ${{ env.new_version }}
          body: |
            ## Changes
            - Description of changes in this release.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}